# Generated by Django 3.2 on 2022-01-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iq', '0005_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='iq.Publication')),
            ],
        ),
    ]
