# Generated by Django 3.2 on 2022-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iq', '0006_article_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(blank=True, null=True, to='iq.Publication'),
        ),
    ]
