# Generated by Django 3.2 on 2022-01-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iq', '0007_auto_20220110_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iq.options')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iq.questions')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
